### ISSUE TITLE
Captcha not working

### ISSUE THREAD

**Issue by rosalinaowo** [hnhx/librebin#1]
As the title says, the captcha isn't working. Even if i open it in another tab it says ".../captcha.php cannot be displayed because it contains errors."
I didn't edit any file and the permission are correctly set for nginx.
![immagine](https://user-images.githubusercontent.com/61975168/171285323-96c6ce62-62db-4023-8193-e03be1d26b2a.png)
Also should the api key be empty or a string?

**Comment by hnhx** [comment]
Hey!

You will need to install / enable the `php-gd` extension to make the captcha work.
For the api key, you can generate a long string and put it in there to bypass the captcha.

**Comment by rosalinaowo** [comment]
Thanks a lot, all working now. Also cool project and website!

**Comment by hnhx** [comment]
Glad you like it!
